# Tm1637.NET Pipeline
# VS Build + Nuget push into internal feed

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Tm1637.NET Variables

name: $(MajorVersion).$(MinorVersion).$(PatchVersion)

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host Building $(MajorVersion).$(MinorVersion).$(PatchVersion)
    errorActionPreference: 'continue'
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Tm1637.NET.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/Tm1637.NET/Tm1637.NET.csproj'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/Tm1637.NET/Tm1637.NET.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: $(MajorVersion)
    minorVersion: $(MinorVersion)
    patchVersion: $(PatchVersion)
    includeSymbols: true
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f1c97239-2d03-4f28-a017-2e548e9ff918'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'nuget'
    publishLocation: 'Container'

